### ISSUE TITLE
使用外部TM以后，第二次打开工程后，空行不能删除，出现如下错误，

### ISSUE THREAD

**Issue by Joe007007007** [xulihang/BasicCAT#21]
使用外部TM以后，第二次打开工程后，空行不能删除，出现如下错误，

error: (NullPointerException) java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.basiccat.opennlp._tokenize(opennlp.java:173)
	at org.xulihang.basiccat.opennlp._lemmatizedsentence(opennlp.java:131)
	at org.xulihang.basiccat.term._termsinasentenceusingiteration(term.java:1327)
	at org.xulihang.basiccat.term._termsinasentence(term.java:1146)
	at org.xulihang.basiccat.project._showterm(project.java:5724)
	at org.xulihang.basiccat.project._targettextarea_focuschanged(project.java:6482)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
什么叫空行不能删除，原文如果分句出来有空行，你可以用删除键做片段合并。这个错误是术语匹配相关的，程序目录下有model这个文件夹吗？你可以把项目传上来看看，或者发邮件给admin@basiccat.org

**Comment by Joe007007007** [comment]
不好意思，的确有点忙。
我是在导入原文，然后用模糊匹配之后，发现有两个空行，我说的不能删除就是用删除键不能合并。因为签的有合同，原文不能外发。后面我再找公开的资料浮现这个问题发给你看。
