### ISSUE TITLE
最新新版本打开项目后弹出异常，之前的版本也有，提示信息见正文

### ISSUE THREAD

**Issue by Joe007007007** [xulihang/BasicCAT#27]
error: (RuntimeException) java.lang.RuntimeException: Object should first be initialized (JavaObject).
StackTrace: java.lang.RuntimeException: Object should first be initialized (JavaObject).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4j.object.JavaObject.getCurrentClass(JavaObject.java:259)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:119)
	at org.xulihang.basiccat.opennlp._tokenize(opennlp.java:230)
	at org.xulihang.basiccat.opennlp._lemmatizedsentence(opennlp.java:188)
	at org.xulihang.basiccat.term._termsinasentenceusingiteration(term.java:1337)
	at org.xulihang.basiccat.term._termsinasentence(term.java:1156)
	at org.xulihang.basiccat.project._showterm(project.java:6725)
	at org.xulihang.basiccat.project._targettextarea_focuschanged(project.java:7592)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
你是执行具体什么操作时出现错误的？我刚重新安装了一遍64位版本没碰到这个问题。

这个问题一般是以下路径没有opennlp的模型文件导致的。

![image](https://user-images.githubusercontent.com/5462205/101328059-7eed2a80-38aa-11eb-9ed7-87442a7afe8d.png)

**Comment by Joe007007007** [comment]
这几个文件都有，在执行指定插件文件夹的时候出现的

**Comment by xulihang** [comment]
选择插件照理和这个没有关系的。
你看下载的安装文件有没有问题，还有运行环境是什么。1.9.6 x64版文件的md5校验码是a8640051f61e5a662babe6f8345f68dc。

如果还有问题我就不清楚了，除非我远程进行调试

**Comment by Joe007007007** [comment]
你用什么方法远程过来调试？等我有空架一个虚拟机复现一下这个问题。

**Comment by xulihang** [comment]
QQ协助或者VNC之类的。虚拟机也可以，给我一个VMWare镜像或者让我远程登录

**Comment by Joe007007007** [comment]
我通过你的gmail:xulihanghai@gmail.com把我的QQ发给你，我们通过qq聊一下怎么调试的问题,请检查一下你的邮箱。谢谢！
