### ISSUE TITLE
软件搜索原文（只是搜索了一次），后切换到另外一个.docx文件后，出现报错

### ISSUE THREAD

**Issue by Joe007007007** [xulihang/BasicCAT#29]
软件搜索原文（只是搜索了一次），后切换到另外一个.docx文件后，出现报错，操作系统 win10 20H2 版本，Basiccat 版本1.9.7

error: (RuntimeException) java.lang.RuntimeException: Object should first be initialized (JavaObject).
StackTrace: java.lang.RuntimeException: Object should first be initialized (JavaObject).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4j.object.JavaObject.getCurrentClass(JavaObject.java:259)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:119)
	at org.xulihang.basiccat.opennlp._tokenize(opennlp.java:230)
	at org.xulihang.basiccat.opennlp._lemmatizedsentence(opennlp.java:188)
	at org.xulihang.basiccat.term._termsinasentenceusingiteration(term.java:1337)
	at org.xulihang.basiccat.term._termsinasentence(term.java:1156)
	at org.xulihang.basiccat.project._showterm(project.java:6725)
	at org.xulihang.basiccat.project._targettextarea_focuschanged(project.java:7601)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xulihang** [comment]
这个问题我没有办法复现

**Comment by xulihang** [comment]
我对术语匹配部分做了修改，试试看新的v1.10.2版是不是没有这个问题了

https://github.com/xulihang/BasicCAT/issues/31

**Comment by Joe007007007** [comment]
好的，谢谢！
