### ISSUE TITLE
JAVA error

### ISSUE THREAD

**Issue by AkiraMishima** [xulihang/BasicCAT#30]
Hello, 

This is mi first time attempting to use BasicCAT. I have JAVA installed, but when I try to save my first project the following error appears:

error: (IllegalStateException) java.lang.IllegalStateException: Interval must be larger than 0.
StackTrace: java.lang.IllegalStateException: Interval must be larger than 0.
	at anywheresoftware.b4a.objects.Timer.setEnabled(Timer.java:76)
	at org.xulihang.basiccat.autosaver._setenabled(autosaver.java:153)
	at org.xulihang.basiccat.main._setautosave(main.java:4404)
	at org.xulihang.basiccat.main._saveproject(main.java:4252)
	at org.xulihang.basiccat.main$ResumableSub_MenuBar1_Action.resume(main.java:3207)
	at org.xulihang.basiccat.main._menubar1_action(main.java:2865)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

Does it depend on me? Thanks.

**Comment by xulihang** [comment]
I haven't met this before. How do you install BasicCAT? Did you download the crossplatform version?

This is caused by a wrong auto save interval setting. You can change it in Preferences.


![image](https://user-images.githubusercontent.com/5462205/103614019-a5ae8780-4f62-11eb-9174-ae2ff31717ba.png)
