### ISSUE TITLE
Exception thrown when oppening a project file the second time

### ISSUE THREAD

**Issue by saulaxel** [xulihang/BasicCAT#31]
SO: Windows 10 Home Single Languages Version 1909
Java: The one included in the instalation
BasicCAT: 1.9.6

No problems when working in a project and its files the first time, but when I open said project again and select a Project File it will show a messege box with the following:
```

error: (RuntimeException) java.lang.RuntimeException: Object should first be initialized (JavaObject).
StackTrace: java.lang.RuntimeException: Object should first be initialized (JavaObject).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4j.object.JavaObject.getCurrentClass(JavaObject.java:259)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:119)
	at org.xulihang.basiccat.opennlp._tokenize(opennlp.java:230)
	at org.xulihang.basiccat.opennlp._lemmatizedsentence(opennlp.java:188)
	at org.xulihang.basiccat.term._termsinasentenceusingiteration(term.java:1337)
	at org.xulihang.basiccat.term._termsinasentence(term.java:1156)
	at org.xulihang.basiccat.project._showterm(project.java:6725)
	at org.xulihang.basiccat.project._targettextarea_focuschanged(project.java:7592)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```

The program doesn't crash, but it keeps showing the same message every time I close it. Meanwhile, the rest of the interface remains blocked, so I cannot ignore the message and start working. It happens when translating from English to Spanish, btw.

**Comment by xulihang** [comment]
I just made some changes after I examined the code related to terms matching: b629901cffba2c846a761a4abc5162d3c16d4302

Try the 1.10.2, it should fix this problem,

**Comment by saulaxel** [comment]
Ok, thanks
