### ISSUE TITLE
Store Problem with BasicCat

### ISSUE THREAD

**Issue by xxnSLN** [xulihang/BasicCAT#64]
I've translated 2 chapters on BasicCat. It closed automatically one day. And then all I have stored and translated on it has gone. Where can I find it? How to guarantee my translation? Thanks.

**Comment by xulihang** [comment]
Please send the project folder to my email: admin@basiccat.org

The translation files are backed up in the bak folder. The translation is saved in the translation memory database. Meanwhile, you can enable git to keep a record of the translation.

So I don't think you will lose your translation.

**Comment by xxnSLN** [comment]
Hi,
A new problem occurred.
It is said an error has happened after i tried to re-edit a term. I cannot close the errorreporter.
error: (PatternSyntaxException) java.util.regex.PatternSyntaxException: Unclosed group near index 23
\b《易传》(《周易大传》)是对《易经》(\b
StackTrace: java.util.regex.PatternSyntaxException: Unclosed group near index 23
\b���״���(�����״󴫡�)�Ƕԡ��׾���(\b
	at java.util.regex.Pattern.error(Pattern.java:1969)
	at java.util.regex.Pattern.accept(Pattern.java:1819)
	at java.util.regex.Pattern.group0(Pattern.java:2922)
	at java.util.regex.Pattern.sequence(Pattern.java:2065)
	at java.util.regex.Pattern.expr(Pattern.java:2010)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init&gt;(Pattern.java:1352)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at anywheresoftware.b4a.keywords.Regex.getPattern(Regex.java:35)
	at anywheresoftware.b4a.keywords.Regex.Matcher2(Regex.java:113)
	at anywheresoftware.b4a.keywords.Regex.Matcher(Regex.java:106)
	at org.xulihang.basiccat.term._termsinasentenceusingiteration(term.java:1349)
	at org.xulihang.basiccat.term._termsinasentence(term.java:1156)
	at org.xulihang.basiccat.project._showterm(project.java:6924)
	at org.xulihang.basiccat.project._targettextarea_focuschanged(project.java:7800)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

Please tell me how to solve this problem.
Thank you!






Sequel
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/BasicCAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月10日(星期五) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xulihang/BasicCAT] Store Problem with BasicCat (Issue #64)





 
Closed #64 as completed.

**Comment by xxnSLN** [comment]
Sequel
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/BasicCAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月10日(星期五) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xulihang/BasicCAT] Store Problem with BasicCat (Issue #64)





 
Closed #64 as completed.

**Comment by xulihang** [comment]
Please open a new issue.
